#!/bin/bash

# Define Cloudflare DNS servers
DNS_IPV4_PRIMARY="1.1.1.1"
DNS_IPV4_SECONDARY="1.0.0.1"
DNS_IPV6_PRIMARY="2606:4700:4700::1111"
DNS_IPV6_SECONDARY="2606:4700:4700::1001"

# Backup the current resolv.conf
sudo cp /etc/resolv.conf /etc/resolv.conf.bak

# Write new DNS settings to resolv.conf
sudo bash -c "cat > /etc/resolv.conf" << EOF
# Generated by DNS update script
nameserver $DNS_IPV4_PRIMARY
nameserver $DNS_IPV4_SECONDARY
nameserver $DNS_IPV6_PRIMARY
nameserver $DNS_IPV6_SECONDARY
EOF

# Ensure the ownership and permissions are correct
sudo chown root:root /etc/resolv.conf
sudo chmod 644 /etc/resolv.conf

echo "DNS settings updated to Cloudflare and permissions fixed."
